apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-serviceaccount
  namespace: production
  labels:
    env: prod
    app: iboats
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::311414082845:role/app-serviceaccount-role
     
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-role
  namespace: production
  labels:
    env: prod
    app: iboats
rules: 
- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["configmaps","secrets","pods"]
  verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-rolebinding
  namespace: production
  labels:
    env: prod
    app: iboats
subjects:
- kind: ServiceAccount
  name: app-serviceaccount
  namespace: production
roleRef:
  kind: Role
  name: app-role
  apiGroup: rbac.authorization.k8s.io

