apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: production
  labels:
    app: iboats
    env: prod
spec:
  type: LoadBalancer
  selector:
    app: iboats
    env: prod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080